### ISSUE TITLE
:Cannot find module 'caliper-sawtooth'

### ISSUE THREAD

**Issue by mlynchbb** [hyperledger/caliper#524]
When trying to run the benchmark tool for the sawtooth simple network example, the containers all load successfully, however when the tool begins testing the following error is encountered:

caliper benchmark run -w ./packages/caliper-samples -c benchmark/simple/config-sawtooth.yaml -n network/sawtooth/simplenetwork/sawtooth.json
.
.
.
nfo: [caliper-flow]: Started monitor successfully
info: [defaultTest]: ####### Testing 'open' #######
info: [defaultTest]: ------ Test round 1 ------
info: [client-util.js]: Launching client with PID  9851
info: [client-util.js]: Waiting for 1 clients to be ready...
info: [client-util.js]: Client ready message recieved
info: [client-util.js]: 1 clients ready, starting test phase
info: [local-client.js]: txUpdateTime: 1000
info: [local-client.js]: Info: client 9851 start test runFixedNumber():opening accounts
error: [sawtooth.js]: invokeSmartContract failed, Error: Unable to load batch builder for simple[1.0] at src/contract/sawtooth/simple/SimpleBatchBuilder.js::Cannot find module 'caliper-sawtooth'

## Context

The SimpleBatchBuilder.js file is calling:

const BatchBuilder = require('caliper-sawtooth').BatchBuilder;

The requirement can't be found, perhaps this is a path problem or some other env setting.  The directory packages/caliper-cli/node_modules/caliper-sawtooth exists with following contents:
index.js  lib  node_modules  package.json  test

## Expected Behavior

The caliper-sawtooth module should be found by SimpleBatchBuilder.js

## Actual Behavior

Cannot find module 'caliper-sawtooth'

## Steps to Reproduce

1. Build with node 10.15.0, 8.12.0 and 8.10.0 and node-gyp  3.6.2 
2. built following https://github.com/hyperledger/caliper/tree/master/packages/caliper-tests-integration (both manual and e2e
3. Fixed Path issue following https://github.com/hyperledger/caliper/issues/481
4.

## Existing issues

- [ ] [Stack Overflow issues](http://stackoverflow.com/tags/hyperledger-caliper)
- [ ] [GitHub Issues](https://github.com/hyperledger/caliper/issues)
- [ ] [Rocket Chat history](https://chat.hyperledger.org/channel/caliper)

## Context

Although the caliper seems to be working for fabric, it is not working for sawtooth.  I am working with sawtooth at this time.

## Your Environment

* Version used:
Amazon EC2 instance
Linux ip-172-31-2-190 4.15.0-1043-aws #45-Ubuntu SMP Mon Jun 24 14:07:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Build with node 10.15.0, 8.12.0 and 8.10.0 and node-gyp  3.6.2 

* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by aklenik** [comment]
Caliper is now published to NPM. That should resolve this require problem, as long as the node_modules dir where Caliper (and the sawtooth package) is installed is in the same or above level from the builder code file.
